// Generated by CoffeeScript 1.7.1

/*
Mithril Preview component

m.component(PreviewComponent, attrs)

attrs:
  head: m.prop "" # head element inner HTMLString
  body: m.prop "" # body element inner HTMLString

require("templateConverter.js")
 */
var PreviewComponent;

PreviewComponent = {
  view: function(ctrl, attrs) {
    return m("iframe", {
      style: "width:100%;height:100%;margin:none;box-sizing:border-box;",
      config: PreviewComponent.config(attrs)
    }, []);
  },
  config: function(attrs) {
    return (function(_this) {
      return function(elm, isInitialized, ctx, vdom) {
        if (!isInitialized) {
          m.mount(elm.contentDocument.head, {
            view: function(_ctrl, _attrs) {
              return PreviewComponent.toVDOM(attrs.head());
            }
          });
          return m.mount(elm.contentDocument.body, {
            view: function(_ctrl, _attrs) {
              return PreviewComponent.toVDOM(attrs.body());
            }
          });
        }
      };
    })(this);
  },
  toVDOM: function(html) {
    var code, err, ret;
    console.log(code = templateConverter.Template(html));
    try {
      console.log(ret = new Function("return " + code)());
    } catch (_error) {
      err = _error;
      console.error(err);
    }
    return ret;
  }
};
